- id: '1545927223051'
  alias: Turn Front Yard Lights On at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id: group.front_yard_lights
    service: switch.turn_on
- id: '1545927387010'
  alias: Turn Front Yard Lights On at Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.front_yard_lights
    service: script.turn_off
