- id: '1546157053732'
  alias: Turn Off the Master Bedroom Heater After 1 Hour
  trigger:
  - entity_id: switch.master_bedroom_heater
    for: '1:00:00'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.master_bedroom_heater
    service: switch.turn_off
