homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_base_url
  login_attempts_threshold: 6
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: warn

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

system_health:
