cch:
  background: 'rgba(41,128,185,.5)'
  header_css: 'backdrop-filter: blur(10px)'
  hide_help: true
  sidebar_closed: true
  swipe: true
resources:
  - type: module
    url: /community_plugin/compact-custom-header/compact-custom-header.js
  - type: js
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: js
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: js
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - type: js
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card.js
  - type: module
    url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
  - type: module
    url: /community_plugin/simple-thermostat/simple-thermostat.js
  - type: module
    url: /community_plugin/popup-backdrop-filter/popup-backdrop-filter.js
title: Home
views:
  - background: var(--background-image)
    badges: []
    cards:
      - decimals: 0
        entity: climate.hallway
        sensors:
          - entity: sensor.hallway_thermostat_humidity
            name: Humidity
        step_size: 1
        type: 'custom:simple-thermostat'
      - color_thresholds:
          - color: '#EF5350'
            value: 260
          - color: '#FFF176'
            value: 190
          - color: '#2196F3'
            value: 80
          - color: '#EF5350'
            value: 0
        entities:
          - sensor.blood_sugar
        hour24: true
        hours_to_show: 6
        points_per_hour: 6
        show:
          labels: hover
        type: 'custom:mini-graph-card'
      - artwork: cover
        entity: media_player.spotify
        hide:
          power: true
          volume: true
        source: icon
        type: 'custom:mini-media-player'
      - card:
          title: People at Home
          type: glance
        filter:
          include:
            - entity_id: person.*
              state: home
        show_empty: false
        type: 'custom:auto-entities'
      - card:
          show_header_toggle: false
          title: Open Doors
          type: glance
        filter:
          include:
            - entity_id: binary_sensor.*_door
              state: 'on'
        show_empty: false
        type: 'custom:auto-entities'
      - card:
          show_header_toggle: false
          title: Media Players
          type: entities
        filter:
          exclude:
            - state: 'off'
            - state: unavailable
            - entity_id: media_player.roku_*
              state: idle
            - entity_id: media_player.spotify
          include:
            - entity_id: media_player.*
              options:
                group: true
                type: 'custom:mini-media-player'
                volume_stateless: false
        show_empty: false
        type: 'custom:auto-entities'
      - cards:
          - entities:
              - head:
                  entity: light.living_room
                  icon: 'mdi:sofa'
                  name: Lights
                  toggle: true
                  type: 'custom:slider-entity-row'
                items:
                  - entity: light.living_room_ceiling_fan_light
                    name: Ceiling Fan Light
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.living_room_indirect_light
                    name: Indirect Light
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.living_room_tall_lamp
                    name: Tall Lamp
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.living_room_small_lamp
                    name: Small Lamp
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.living_room_square_lamp
                    name: Square Lamp
                    toggle: true
                    type: 'custom:slider-entity-row'
                type: 'custom:fold-entity-row'
            show_header_toggle: false
            title: Living Room
            type: entities
          - columns: 3
            entities:
              - entity: switch.breath_of_the_wild_poster
                icon: 'mdi:image-frame'
                name: Poster
                tap_action:
                  action: toggle
              - entity: switch.living_room_candle_warmer
                icon: 'mdi:candle'
                name: Candle Warmer
                tap_action:
                  action: toggle
              - entity: media_player.sony_bravia_tv
                icon: 'mdi:television'
                name: TV
                tap_action:
                  action: toggle
              - entity: light.back_room_main_lights
                name: Back Room
                tap_action:
                  action: toggle
              - binary_sensor.inner_back_door
              - binary_sensor.outer_back_door
            type: glance
        type: 'custom:vertical-stack-in-card'
      - entities:
          - entity: light.hallway_main_lights
            name: Lights
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: light.front_bathroom_vanity_lights
            icon: 'mdi:shower'
            name: Bathroom Lights
            toggle: true
            type: 'custom:slider-entity-row'
        show_header_toggle: false
        title: Hallway
        type: entities
      - cards:
          - entities:
              - entity: light.front_hallway_main_lights
                name: Lights
                toggle: true
                type: 'custom:slider-entity-row'
            show_header_toggle: false
            title: Front Hallway
            type: entities
          - entities:
              - entity: lock.front_door
                name: Front Door Lock
              - binary_sensor.front_door
            type: glance
        type: 'custom:vertical-stack-in-card'
      - cards:
          - entities:
              - head:
                  entity: light.kitchen_light_group
                  name: Lights
                  toggle: true
                  type: 'custom:slider-entity-row'
                items:
                  - entity: light.kitchen_main_lights
                    name: Main Lights
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.kitchen_sink_light
                    name: Sink Light
                    toggle: true
                    type: 'custom:slider-entity-row'
                type: 'custom:fold-entity-row'
            show_header_toggle: false
            title: Kitchen
            type: entities
          - entities:
              - sensor.coffee_maker_state
            type: glance
        type: 'custom:vertical-stack-in-card'
      - entities:
          - head:
              entity: light.master_bedroom_light_group
              icon: 'mdi:hotel'
              name: Lights
              toggle: true
              type: 'custom:slider-entity-row'
            items:
              - entity: light.master_bedroom_ceiling_fan_light
                name: Ceiling Fan Light
                toggle: true
                type: 'custom:slider-entity-row'
              - head:
                  entity: light.master_bedroom_lamp_group
                  icon: 'mdi:lamp'
                  name: Lamps
                  toggle: true
                  type: 'custom:slider-entity-row'
                items:
                  - entity: light.master_bedroom_gabe_lamp
                    name: Gabe
                    toggle: true
                    type: 'custom:slider-entity-row'
                  - entity: light.master_bedroom_liv_lamp
                    name: Liv
                    toggle: true
                    type: 'custom:slider-entity-row'
                type: 'custom:fold-entity-row'
            type: 'custom:fold-entity-row'
          - head:
              entity: light.master_bathroom_light_group
              icon: 'mdi:shower'
              name: Bathroom Lights
              toggle: true
              type: 'custom:slider-entity-row'
            items:
              - entity: light.master_bathroom_vanity_lights
                name: Vanity Lights
                toggle: true
                type: 'custom:slider-entity-row'
              - entity: light.master_bathroom_toilet_light
                name: Toilet Light
                toggle: true
                type: 'custom:slider-entity-row'
              - entity: light.master_bathroom_shower_light
                name: Shower Light
                toggle: true
                type: 'custom:slider-entity-row'
              - entity: light.master_closet_lights
                icon: 'mdi:hanger'
                name: Closet Lights
                toggle: true
                type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entity: fan.master_bedroom_ceiling_fan
            name: Ceiling Fan
            toggle: true
            type: 'custom:slider-entity-row'
          - entity: switch.master_bedroom_fireplace
            name: Fireplace
          - entity: input_select.master_bedroom_relax_sounds
        show_header_toggle: false
        title: Master Bedroom
        type: entities
      - entities:
          - head:
              entity: light.study_light_group
              icon: 'mdi:keyboard'
              name: Lights
              toggle: true
              type: 'custom:slider-entity-row'
            items:
              - entity: light.study_ceiling_fan_light
                name: Ceiling Fan Light
                toggle: true
                type: 'custom:slider-entity-row'
              - entity: light.study
                name: Lamps
                toggle: true
                type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entity: fan.study_ceiling_fan
            name: Ceiling Fan
            toggle: true
            type: 'custom:slider-entity-row'
        show_header_toggle: false
        title: Study
        type: entities
      - cards:
          - entities:
              - entity: light.laundry_room_main_lights
                name: Lights
                toggle: true
                type: 'custom:slider-entity-row'
            show_header_toggle: false
            title: Laundry Room
            type: entities
          - entities:
              - sensor.washer_state
              - binary_sensor.laundry_room_door
            type: glance
        type: 'custom:vertical-stack-in-card'
      - entities:
          - entity: light.front_yard_light_group
            name: Front Yard Lights
            tap_action:
              action: toggle
          - entity: light.side_yard_light
            tap_action:
              action: toggle
        show_icon: true
        show_state: true
        title: Outside
        type: glance
      - entities:
          - entity: light.garage_main_lights
            tap_action:
              action: toggle
          - entity: cover.garage_door
          - entity: binary_sensor.side_door
        title: Garage
        type: glance
    icon: 'mdi:home'
    path: home
    title: Home
  - background: var(--background-image)
    badges: []
    cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - hold_action:
          action: none
        image: >-
          https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=TLX&brand=wui&num=12&delay=50&type=N0R&frame=0&scale=1&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0
        tap_action:
          action: none
        type: picture
    icon: 'mdi:weather-partlycloudy'
    path: weather
    title: Weather
  - background: var(--background-image)
    badges: []
    cards:
      - cards:
          - entity: camera.wyze
            type: picture-entity
          - entities:
              - sensor.wyze_light_sensor
              - switch.wyze_ir_filter
              - switch.wyze_ir_led
              - switch.wyze_night_mode
              - switch.wyze_night_mode_auto
              - switch.wyze_blue_led
              - switch.wyze_yellow_led
              - switch.wyze_motion_detection
              - switch.wyze_motion_tracking
              - camera.wyze_motion_snapshot
              - binary_sensor.wyze_motion_sensor
            type: entities
        type: 'custom:vertical-stack-in-card'
    icon: 'mdi:camera'
    path: camera
    title: Camera
  - background: var(--background-image)
    badges: []
    cards:
      - entity: switch.eccleston
        hold_action:
          action: more-info
        icon_height: 48px
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: entity-button
      - card:
          show_header_toggle: false
          title: Router Stats
          type: entities
        filter:
          include:
            - entity_id: sensor.asuswrt_*
        show_empty: false
        type: 'custom:auto-entities'
      - card:
          show_header_toggle: false
          title: PiHole Stats
          type: entities
        entities:
          - switch.pihole_state
        filter:
          include:
            - entity_id: sensor.pi_hole_*
        type: 'custom:auto-entities'
      - card:
          show_header_toggle: false
          title: Deluge Stats
          type: entities
        entities:
          - switch.deluge_state
        filter:
          include:
            - entity_id: sensor.deluge_*
        type: 'custom:auto-entities'
      - entities:
          - entity: sensor.home_to_work_travel_time
            icon: 'mdi:briefcase'
          - entity: sensor.work_to_home_travel_time
            icon: 'mdi:home'
        title: Travel Time
        type: glance
    icon: 'mdi:dots-horizontal'
    panel: false
    path: other
    title: Other
