esphome:
  name: $entity_id
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  # Physical button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    name: "${device_name} Physical Button"
    id: physical_button
    internal: true
    on_press:
      - switch.turn_on: relay

cover:
  # Garage door cover
  - platform: template
    name: "${device_name}"
    id: garage_door_cover
    device_class: garage
    open_action:
      # Only run open_action if the door is CLOSED
      - if:
          condition:
            lambda: 'return id(garage_door_cover).position == COVER_CLOSED;'
          then:
            - switch.turn_on: relay
    close_action:
      # Only run close_action if the door is OPEN
      - if:
          condition:
            lambda: 'return id(garage_door_cover).position == COVER_OPEN;'
          then:
            - switch.turn_on: relay

sensor:
  # Ultrasonic distance sensor
  - platform: ultrasonic
    trigger_pin: GPIO12
    echo_pin: GPIO14
    name: "${device_name} Distance"
    id: distance
    update_interval: 500ms
    unit_of_measurement: cm
    timeout: 3m
    pulse_time: 20us
    filters:
      # Convert m to cm
      - multiply: 100
      # Take median of the last 5 values
      # https://github.com/esphome/esphome/blob/0fc267dfc734c16868c8801d4e85782cc4e19f1f/esphome/components/sensor/filter.cpp#L42-L76
      - lambda: |-
          static std::deque<float> queue_;

          while (queue_.size() >= 20) {
            queue_.pop_front();
          }
          queue_.push_back(x);

          float median = 0.0f;
          if (!queue_.empty()) {
            std::deque<float> median_queue = queue_;
            sort(median_queue.begin(), median_queue.end());
            size_t queue_size = median_queue.size();

            if (queue_size % 2) {
              median = median_queue[queue_size / 2];
            } else {
              median = (median_queue[queue_size / 2] + median_queue[(queue_size / 2) - 1]) / 2.0f;
            }
          }
          return median;
      - delta: 5
    on_value_range:
      # Garage door is OPEN if x < 30cm
      - below: 30
        then:
          - cover.template.publish:
              id: garage_door_cover
              state: OPEN
      # Garage door is CLOSED if x > 29cm
      - above: 29
        then:
          - cover.template.publish:
              id: garage_door_cover
              state: CLOSED
      # Car is not_home if  x > 139cm
      - above: 139
        then:
          - homeassistant.service:
              service: mqtt.publish
              data:
                topic: "location/car/${person}"
                payload: not_home
                retain: "true"
      # Car is home if 49cm < x < 140cm
      - above: 49
        below: 140
        then:
          - homeassistant.service:
              service: mqtt.publish
              data:
                topic: "location/car/${person}"
                payload: home
                retain: "true"

status_led:
  pin:
    number: GPIO2
    inverted: true

switch:
  # Garage door opener relay
  - platform: gpio
    pin: GPIO15
    name: $device_name
    id: relay
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      # Only pulse on for 500ms
      - delay: 500ms
      - switch.turn_off: relay

<<: !include common.yaml
