esphome:
  name: $entity_id
  platform: ESP8266
  board: esp01_1m

uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    pin: GPIO12
    name: $device_name
    id: relay
    restore_mode: $relay_restore_mode

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    id: button
    internal: true
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

sensor:
  - platform: cse7766
    current:
      name: "${device_name} Current"
      filters:
        - exponential_moving_average:
            alpha: 0.5
            send_every: 3
        - delta: 0.1
    power:
      name: "${device_name} Power"
      filters:
        - exponential_moving_average:
            alpha: 0.5
            send_every: 3
        - delta: 0.5
    voltage:
      name: "${device_name} Voltage"
      filters:
        - exponential_moving_average:
            alpha: 0.5
            send_every: 3
        - delta: 0.5
    update_interval: 2s

<<: !include common.yaml
