substitutions:
  entity_id: coffee_maker
  device_name: Coffee Maker
  api_password: !secret coffee_maker_api_password
  ota_password: !secret coffee_maker_ota_password
  relay_restore_mode: RESTORE_DEFAULT_OFF

<<: !include device_types/s31.yaml
