substitutions:
  entity_id: security_system
  device_name: Security System
  api_password: !secret security_system_api_password
  ota_password: !secret security_system_ota_password

esphome:
  name: $entity_id
  platform: ESP8266
  board: nodemcuv2

binary_sensor:
  # Motion sensor
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: "${device_name} Motion"
    device_class: motion

switch:
  # Siren relay
  - platform: gpio
    pin: D8
    name: "${device_name} Siren"
    icon: "mdi:alarm-bell"
    id: relay
    restore_mode: ALWAYS_OFF

<<: !include device_types/common.yaml
