homeassistant:
  customize:
    switch.deluge_state:
      icon: mdi:download

google_assistant:
  entity_config:
    switch.deluge_state:
      expose: true
      aliases:
        - Deluge

sensor:
  - platform: deluge
    host: !secret deluge_host
    username: !secret deluge_user
    password: !secret deluge_password
    monitored_variables:
      - current_status
      - download_speed
      - upload_speed

switch:
  - platform: deluge
    name: Deluge State
    host: !secret deluge_host
    username: !secret deluge_user
    password: !secret deluge_password