google_assistant:

  entity_config:
    switch.coffee_maker:
      expose: true
      aliases:
        - Coffee Maker
      room: Kitchen

homeassistant:
  customize:
    switch.coffee_maker:
      friendly_name: Coffee Maker
      icon: mdi:coffee
    sensor.coffee_maker_apparent:
      friendly_name: Coffee Maker Apparent
      icon: mdi:flash-circle
    sensor.coffee_maker_current:
      friendly_name: Coffee Maker Current
      icon: mdi:flash-circle
    sensor.coffee_maker_energy:
      friendly_name: Coffee Maker Energy
    sensor.coffee_maker_factor:
      friendly_name: Coffee Maker Factor
    sensor.coffee_maker_power:
      friendly_name: Coffee Maker Power
      icon: mdi:flash-circle
    sensor.coffee_maker_voltage:
      friendly_name: Coffee Maker Voltage
      icon: mdi:flash-circle
    switch.washer:
      friendly_name: Washer
      icon: mdi:washing-machine
    sensor.washer_apparent:
      friendly_name: Washer Apparent
      icon: mdi:flash-circle
    sensor.washer_current:
      friendly_name: Washer Current
      icon: mdi:flash-circle
    sensor.washer_energy:
      friendly_name: Washer Energy
    sensor.washer_factor:
      friendly_name: Washer Factor
    sensor.washer_power:
      friendly_name: Washer Power
      icon: mdi:flash-circle
    sensor.washer_voltage:
      friendly_name: Washer Voltage
      icon: mdi:flash-circle

group:
  washer:
      name: Washer
      entities:
        - switch.washer
        - sensor.washer_state
        - sensor.washer_current
        - sensor.washer_voltage
        - sensor.washer_power
        - sensor.washer_apparent
        - sensor.washer_energy
        - sensor.washer_factor

  coffee_maker:
      name: Coffee Maker
      entities:
        - switch.coffee_maker
        - sensor.coffee_maker_state
        - sensor.coffee_maker_current
        - sensor.coffee_maker_voltage
        - sensor.coffee_maker_power
        - sensor.coffee_maker_apparent
        - sensor.coffee_maker_energy
        - sensor.coffee_maker_factor

sensor:
  ##########
  # Washer #
  ##########

  - platform: mqtt
    name: "Washer State"
    state_topic: "hass/state/washer"
    icon: mdi:washing-machine
  # - platform: mqtt
    # name: "Washer Watts"
    # state_topic: "tele/washer/SENSOR"
    # value_template: "{{ value_json['ENERGY'].Power }}"
    # qos: 2
    # unit_of_measurement : "W"
    # icon: mdi:flash-circle
    # availability_topic: "tele/washer/LWT"
    # payload_available: "Online"
    # payload_not_available: "Offline"
  # - platform: mqtt
    # name: "Washer Voltage"
    # state_topic: "tele/washer/SENSOR"
    # value_template: "{{ value_json['ENERGY'].Voltage }}"
    # qos: 2
    # unit_of_measurement : "V"
    # icon: mdi:flash-circle
    # availability_topic: "tele/washer/LWT"
    # payload_available: "Online"
    # payload_not_available: "Offline"
  # - platform: mqtt
    # name: "Washer Amps"
    # state_topic: "tele/washer/SENSOR"
    # value_template: "{{ value_json['ENERGY'].Current }}"
    # qos: 2
    # unit_of_measurement : "A"
    # icon: mdi:flash-circle
    # availability_topic: "tele/washer/LWT"
    # payload_available: "Online"
    # payload_not_available: "Offline"
  # - platform: mqtt
    # name: "Washer Energy Today"
    # state_topic: "tele/washer/SENSOR"
    # value_template: "{{ value_json['ENERGY'].Today }}"
    # qos: 2
    # unit_of_measurement : "kWh"
    # availability_topic: "tele/washer/LWT"
    # payload_available: "Online"
    # payload_not_available: "Offline"
  # - platform: mqtt
    # name: "Washer Energy Yesterday"
    # state_topic: "tele/washer/SENSOR"
    # value_template: "{{ value_json['ENERGY'].Yesterday }}"
    # qos: 2
    # unit_of_measurement : "kWh"
    # availability_topic: "tele/washer/LWT"
    # payload_available: "Online"
    # payload_not_available: "Offline"
  # - platform: mqtt
    # state_topic: "tele/washer/STATE"
    # name: "Washer Signal"
    # unit_of_measurement: "%"
    # value_template: "{{ value_json['Wifi'].RSSI }}"
    # availability_topic: "tele/washer/LWT"
    # qos: 1
    # payload_available: "Online"
    # payload_not_available: "Offline"

  ################
  # Coffee Maker #
  ################

  - platform: mqtt
    name: "Coffee Maker State"
    state_topic: "hass/state/coffee"
    icon: mdi:coffee
  # - platform: mqtt
    #  name: "Coffee Maker Watts"
    #  state_topic: "tele/coffee/SENSOR"
    #  value_template: "{{ value_json['ENERGY'].Power }}"
    #  qos: 2
    #  unit_of_measurement : "W"
    #  icon: mdi:flash-circle
    #  availability_topic: "tele/coffee/LWT"
    #  payload_available: "Online"
    #  payload_not_available: "Offline"
  # - platform: mqtt
    #  name: "Coffee Maker Voltage"
    #  state_topic: "tele/coffee/SENSOR"
    #  value_template: "{{ value_json['ENERGY'].Voltage }}"
    #  qos: 2
    #  unit_of_measurement : "V"
    #  icon: mdi:flash-circle
    #  availability_topic: "tele/coffee/LWT"
    #  payload_available: "Online"
    #  payload_not_available: "Offline"
  # - platform: mqtt
    #  name: "Coffee Maker Amps"
    #  state_topic: "tele/coffee/SENSOR"
    #  value_template: "{{ value_json['ENERGY'].Current }}"
    #  qos: 2
    #  unit_of_measurement : "A"
    #  icon: mdi:flash-circle
    #  availability_topic: "tele/coffee/LWT"
    #  payload_available: "Online"
    #  payload_not_available: "Offline"
  # - platform: mqtt
    #  name: "Coffee Maker Energy Today"
    #  state_topic: "tele/coffee/SENSOR"
    #  value_template: "{{ value_json['ENERGY'].Today }}"
    #  qos: 2
    #  unit_of_measurement : "kWh"
    #  availability_topic: "tele/coffee/LWT"
    #  payload_available: "Online"
    #  payload_not_available: "Offline"
  # - platform: mqtt
    #  name: "Coffee Maker Energy Yesterday"
    #  state_topic: "tele/coffee/SENSOR"
    #  value_template: "{{ value_json['ENERGY'].Yesterday }}"
    #  qos: 2
    #  unit_of_measurement : "kWh"
    #  availability_topic: "tele/coffee/LWT"
    #  payload_available: "Online"
    #  payload_not_available: "Offline"
  # - platform: mqtt
    #  state_topic: "tele/coffee/STATE"
    #  name: "Coffee Maker Signal"
    #  unit_of_measurement: "%"
    #  value_template: "{{ value_json['Wifi'].RSSI }}"
    #  availability_topic: "tele/coffee/LWT"
    #  qos: 1
    #  payload_available: "Online"
    #  payload_not_available: "Offline"