google_assistant:
  entity_config:
    cover.garage_door:
      expose: true
      aliases:
        - Garage Door
        - Garage
      room: Garage

homeassistant:
  customize:
    device_tracker.gabe_car:
      source_type: router
