cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: Garage Door
        value_template: "{{ states('sensor.garage_door_sr04_distance')|float < 50 }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garage_door

device_tracker:
  - platform: mqtt
    devices:
      gabe_car: 'location/car/gabe'

google_assistant:
  entity_config:
    cover.garage_door:
      expose: true
      aliases:
        - Garage Door
        - Garage
      room: Garage

homeassistant:
  customize:
    cover.garage_door:
      device_class: garage
    device_tracker.gabe_car:
      source_type: router