cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: Garage Door
        value_template: >
          {{ (not is_state('sensor.garage_door_sr04_distance', 'unavailable')) and states('sensor.garage_door_sr04_distance')|float < 50 }}
        open_cover:
          service_template: "switch.turn_{{ 'off' if states('cover.garage_door') == 'open' else 'on' }}"
          data:
            entity_id: switch.garage_door
        close_cover:
          service_template: "switch.turn_{{ 'off' if states('cover.garage_door') == 'closed' else 'on' }}"
          data:
            entity_id: switch.garage_door

device_tracker:
  - platform: mqtt
    devices:
      gabe_car: 'location/car/gabe'

google_assistant:
  entity_config:
    cover.garage_door:
      expose: true
      aliases:
        - Garage Door
        - Garage
      room: Garage

homeassistant:
  customize:
    device_tracker.gabe_car:
      source_type: router