homeassistant:
  customize_glob:
    light.*_lamp:
      icon: mdi:lamp
    light.living_room_indirect_light*:
      icon: mdi:ceiling-light
    light.living_room_ceiling_fan_light*:
      icon: mdi:ceiling-light
    light.living_room_tall_lamp*:
      icon: mdi:floor-lamp
  customize:
    light.master_bathroom_toilet_light:
      icon: mdi:toilet
    light.master_bathroom_shower_light:
      icon: mdi:shower
