homeassistant:
  customize:
    light.master_bedroom_ceiling_fan_light:
      icon: mdi:ceiling-light
    light.study_ceiling_fan_light:
      icon: mdi:keyboard
    light.kitchen_lights:
      icon: mdi:fridge
    light.hallway_main_lights:
      icon: mdi:ceiling-light
    light.front_hallway_main_lights:
      icon: mdi:ceiling-light
    light.laundry_room_main_lights:
      icon: mdi:ceiling-light
    light.master_bathroom_vanity_lights:
      icon: mdi:wall-sconce
    light.driveway_lights:
      icon: mdi:wall-sconce
    light.front_porch_lights:
      icon: mdi:ceiling-light
    light.side_yard_light:
      icon: mdi:wall-sconce
    light.back_room_main_lights:
      icin: mdi:ceiling-light

light:
  - platform: switch
    entity_id: switch.back_room_main_lights
    name: Back Room Main Lights

  - platform: switch
    entity_id: switch.driveway_lights
    name: Driveway Lights

  - platform: switch
    entity_id: switch.garage_main_lights
    name: Garage Main Lights

  - platform: switch
    entity_id: switch.front_porch_lights
    name: Front Porch Lights

  - platform: switch
    entity_id: switch.side_yard_light
    name: Side Yard Light

  - platform: group
    entities:
      - light.front_porch_lights
      - light.driveway_lights
    name: Front Yard Light Group

lutron_caseta_pro:
  bridges:
    - host: !secret lutron_caseta_pro_host
      mac: !secret lutron_caseta_pro_mac
      fan:
        - 15
        - 18
      switch:
        - 19
        - 20
        - 21
        - 22
        - 23

google_assistant:
  entity_config:

    ############
    # Driveway #
    ############
    switch.driveway_lights:
      expose: true
      aliases:
        - Driveway Lights
      room: Driveway

    #############
    # Side Yard #
    #############
    switch.side_yard_light:
      expose: true
      aliases:
        - Side Yard Light
      room: Side Yard

    ###############
    # Front Porch #
    ###############
    switch.front_porch_lights:
      expose: true
      aliases:
        - Front Porch Lights
      room: Front Porch

    ###########
    # Kitchen #
    ###########
    light.kitchen_main_lights: 
      expose: true
      aliases:
        - Kitchen Main Lights
      room: Kitchen

    #################
    # Front Hallway #
    #################
    light.front_hallway_main_lights:
      expose: true
      aliases:
        - Front Hallway Lights
      room: Front Hallway

    #############
    # Back Room #
    #############
    switch.back_room_main_lights:
      expose: true
      aliases:
        - Back Room Lights
        - Tortilla Room
      room: Back Room

    ###########
    # Hallway #
    ###########
    light.hallway_main_lights: 
      expose: true
      aliases:
        - Hallway Lights
      room: Hallway
    
    light.front_bathroom_vanity_lights:
      expose: true
      aliases:
        - Front Bathroom Lights
      room: Front Bathroom

    ################
    # Laundry Room #
    ################
    light.laundry_room_main_lights: 
      expose: true
      aliases:
        - Laundry Room Lights
      room: Laundry Room

    ##########
    # Garage #
    ##########
    switch.garage_main_lights: 
      expose: true
      aliases:
        - Garage Lights
      room: Garage

    #########
    # Study #
    #########
    light.study_ceiling_fan_light: 
      expose: true
      aliases:
        - Study Ceiling Fan Light
        - Ceiling Fan Light
      room: Study

    fan.study_ceiling_fan:
      expose: true
      aliases:
        - Study Ceiling Fan
        - Ceiling Fan
      room: Study

    ##################
    # Master Bedroom #
    ##################
    light.master_bedroom_ceiling_fan_light: 
      expose: true
      aliases:
        - Master Bedroom Ceiling Fan Light
        - Ceiling Fan Light
      room: Master Bedroom

    fan.master_bedroom_ceiling_fan:
      expose: true
      aliases:
        - Master Bedroom Ceiling Fan
        - Ceiling Fan
      room: Master Bedroom

    ###################
    # Master Bathroom #
    ###################
    light.master_bathroom_vanity_lights:
      expose: true
      aliases:
        - Master Bathroom Vanity Lights
      room: Master Bathroom

    light.master_closet_lights:
      expose: true
      aliases:
        - Master Closet Lights
      room: Master Bathroom