homeassistant:
  customize:
    light.master_bedroom_ceiling_fan_light:
      icon: mdi:ceiling-light
    light.study_ceiling_fan_light:
      icon: mdi:keyboard
    light.kitchen_lights:
      icon: mdi:fridge
    light.hallway_main_lights:
      icon: mdi:ceiling-light
    light.front_hallway_main_lights:
      icon: mdi:ceiling-light
    light.laundry_room_main_lights:
      icon: mdi:ceiling-light
    light.master_bathroom_vanity_lights:
      icon: mdi:wall-sconce

lutron_caseta_pro:
  bridges:
    - host: !secret lutron_caseta_pro_host
      mac: !secret lutron_caseta_pro_mac
      fan:
        - 15

google_assistant:
  entity_config:

    ###########
    # Kitchen #
    ###########
    light.kitchen_main_lights: 
      expose: true
      aliases:
        - Main Lights
      room: Kitchen

    #################
    # Front Hallway #
    #################
    light.front_hallway_main_lights:
      expose: true
      aliases:
        - Main Lights
      room: Front Hallway

    ###########
    # Hallway #
    ###########
    light.hallway_main_lights: 
      expose: true
      aliases:
        - Main Lights
      room: Hallway

    ################
    # Laundry Room #
    ################
    light.laundry_room_main_lights: 
      expose: true
      aliases:
        - Main Lights
      room: Laundry Room

    #########
    # Study #
    #########
    light.study_ceiling_fan_light: 
      expose: true
      aliases:
        - Ceiling Fan Light
      room: Study

    ##################
    # Master Bedroom #
    ##################
    light.master_bedroom_ceiling_fan_light: 
      expose: true
      aliases:
        - Ceiling Fan Light
      room: Master Bedroom
    fan.master_bedroom_ceiling_fan:
      expose: true
      aliases:
        - Ceiling Fan
      room: Master Bedroom

    ###################
    # Master Bathroom #
    ###################
    light.master_bathroom_vanity_lights:
      expose: true
      aliases:
        - Vanity Lights
      room: Master Bathroom
