cover:
  - platform: opengarage
    covers:
      garage:
        host:  !secret opengarage_host
        device_key: !secret opengarage_device_key
        name:  Garage Door

device_tracker:
  - platform: mqtt
    devices:
      gabe_car: 'location/car/gabe'

google_assistant:
  entity_config:
    cover.garage_door:
      expose: true
      aliases:
        - Garage Door
        - Garage
      room: Garage

homeassistant:
  customize:
    device_tracker.gabe_car:
      source_type: router