group:
  all_people:
    - person.gabe
    - person.liv
    - person.maya

homeassistant:
  customize:
    person.gabe:
      entity_picture: /local/pictures/gabe.jpg
    person.liv:
      entity_picture: /local/pictures/liv.jpg
    person.maya:
      entity_picture: /local/pictures/maya.jpg

person:
  - name: Gabe
    id: gabe
    user_id: !secret person_gabe_user_id
    device_trackers: !secret person_gabe_device_trackers

  - name: Liv
    id: liv
    device_trackers: !secret person_liv_device_trackers
  
  - name: Maya
    id: maya
    device_trackers: !secret person_maya_device_trackers
