homeassistant:
  customize:
    person.gabe:
      entity_picture: /local/pictures/gabe.jpg
    person.liv:
      entity_picture: /local/pictures/liv.jpg
    person.maya:
      entity_picture: /local/pictures/maya.jpg

person:
  - name: Gabe
    id: Gabe
    user_id: !secret gabe_user_id
    device_trackers:
      - device_tracker.gabe_phone
      - device_tracker.gabe_car

  - name: Liv
    id: liv
    device_trackers:
      - device_tracker.liv_phone
  
  - name: Maya
    id: maya
    device_trackers:
      - device_tracker.maya_phone