google_assistant:
  entity_config:
    switch.pihole_state:
      expose: true
      aliases:
        - Ad Blocker
        - Pi-Hole

homeassistant:
  customize:
    switch.pihole_state:
      icon: mdi:cancel

pi_hole:
    host: !secret pihole_host

switch:
  - platform: command_line
    switches:
      pihole_state:
        friendly_name: Pi-Hole State
        command_on: !secret pihole_command_on
        command_off: !secret pihole_command_off
        command_state: !secret pihole_command_state
        value_template: "{{ value_json.status == 'enabled' }}"
