google_assistant:
  entity_config:
    switch.living_room_candle_warmer:
      expose: true
      aliases:
        - Candle Warmer
      room: Living Room

    switch.master_bedroom_fireplace:
      expose: true
      aliases:
        - Fireplace
        - Space Heater
        - Heater
      room: Master Bedroom

    # switch.master_bedroom_heated_blanket:
    #   expose: true
    #   aliases:
    #     - Heated Blanket
    #   room: Master Bedroom

homeassistant:
  customize:
    switch.master_bedroom_fireplace:
      icon: mdi:radiator

tplink:
  discovery: false
  switch:
    - host: 192.168.1.21
    # - host: 192.168.1.29
    # - host: 192.168.1.31
    # - host: 192.168.1.32
    - host: 192.168.1.39
    - host: 192.168.1.96
    # - host: 192.168.1.210