google_assistant:
  entity_config:
    switch.living_room_candle_warmer:
      expose: true
      aliases:
        - Candle Warmer
      room: Living Room

    switch.master_bedroom_fireplace:
      expose: true
      aliases:
        - Fireplace
        - Space Heater
        - Heater
      room: Master Bedroom

    # switch.master_bedroom_heated_blanket:
    #   expose: true
    #   aliases:
    #     - Heated Blanket
    #   room: Master Bedroom

homeassistant:
  customize:
    switch.master_bedroom_fireplace:
      icon: mdi:radiator

tplink:
  discovery: false
  switch: !secret tplink_switch_hosts