sensor:
  - platform: waze_travel_time
    name: Home to Work Travel Time
    origin: zone.home
    destination: zone.work
    region: US

  - platform: waze_travel_time
    name: Work to Home Travel Time
    origin: zone.home
    destination: zone.work
    region: US
