homeassistant:
  customize:
    switch.eccleston:
      icon: mdi:desktop-classic

switch:
  - platform: wake_on_lan
    mac_address: d8:cb:8a:31:85:a4
    name: eccleston
    host: 192.168.1.63
    scan_interval: 2