homeassistant:
  customize:
    switch.eccleston:
      icon: mdi:desktop-classic

switch:
  - platform: wake_on_lan
    mac_address: !secret eccleston_mac
    name: eccleston
    host: !secret eccleston_host
    scan_interval: 2